name: FloatingTexter
main: FloatingTexter\Main
version: "2.0"
api: [1.12.0]
description: Easily add floating text to your PocketMine server!
website: https://github.com/Heromine/FloatingTexter
author: Heromine/Jon, Flavius12, AryToNeX
