---
# FloatingTexter Config File
floats:
  floatname:
   text:
    - "Line 1"
    - "Line 2"
    - "Line 3"
    - "More lines"
    - "I Like Nutella"
   level: "world"
   x: 128
   y: 64
   z: 128
  examplefloat:
   text:
    - "Welcome to my server!"
    - "Enjoy!"
   level: "world"
   x: 120
   y: 64
   z: 128
...
